### ISSUE TITLE
Move to CircleCI

### ISSUE THREAD

**Issue by keathley** [elixir-wallaby/wallaby#418]
Let's move our CI setup to circle and off of travis. We should attempt to make our builds more reliable so that we don't spend a bunch of time dealing with false positives because selenium couldn't be installed or something similar.

**Comment by michallepicki** [comment]
What are the advantages of CircleCI over Travis in regards to reliablity?

We've been using CircleCI for running Selenium tests at work. For Selenium we're using the official docker images: https://github.com/SeleniumHQ/docker-selenium and a custom bash script for waiting for it to start up. Docker caches seem to work reliably for us so there's no way selenium "couldn't be installed" this way.

Overall CircleCI works OK, jobs are running fine, but the UI (the webapp) is not the most responsive in the world - I'm often seeing a "Servers are overloaded" or "Something went wrong" message. Additionally, recently there are often warnings about "Degraded GitHub notifications service" or "GCP Networking issues", but these haven't affected us in any way.

**Comment by keathley** [comment]
I picked circle out of general familiarity. Overall its been more reliable then I've ever seen travis be. We've been considering a move for a while and Travis is under new management now so the timing seemed right.

**Comment by mhanberg** [comment]
In general I like CircleCI more than Travis, but i'm not sure it has a good support for the version matrix.

I feel like it is very useful for open source libraries to be able to easily test under different versions of the language, and Elixir especially since it relies on Erlang versions as well.

**Comment by mhanberg** [comment]
I ran across some documentation which shows how to create a build matrix using CircleCI workflows: https://discuss.circleci.com/t/build-matrix-configuration/14448

**Comment by mhanberg** [comment]
GitHub Actions might also be a good CI platform to use. I believe that open source projects getting unlimited build minutes and unlimited parallel workflows

**Comment by mhanberg** [comment]
We moved to GitHub Actions in #484
