### ISSUE TITLE
Wallaby >= 0.19.2 crashes with poolboy timeout at startup

### ISSUE THREAD

**Issue by AndroidOatmeal** [elixir-wallaby/wallaby#423]
## Issue

After bumping my wallaby version from 0.19.1 to 0.19.2, I began to see consistent poolboy timeout errors during wallaby's startup.

The error message is:
```
13:58:41.462 [error] GenServer #PID<0.985.0> terminating
** (MatchError) no match of right hand side value: {:error, {:timeout, {Task, :await, [%Task{owner: #PID<0.986.0>, pid: #PID<0.988.0>, ref: #Reference<0.1593646549.2667839490.39908>}, 5000]}}}
    (poolboy) /Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl:283: :poolboy.new_worker/1
    (poolboy) /Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl:304: :poolboy.prepopulate/3
    (poolboy) /Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl:153: :poolboy.init/3
    (stdlib) gen_server.erl:374: :gen_server.init_it/2
    (stdlib) gen_server.erl:342: :gen_server.init_it/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:EXIT, #PID<0.984.0>, {{:badmatch, {:error, {:timeout, {Task, :await, [%Task{owner: #PID<0.986.0>, pid: #PID<0.988.0>, ref: #Reference<0.1593646549.2667839490.39908>}, 5000]}}}}, [{:poolboy, :new_worker, 1, [file: '/Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl', line: 283]}, {:poolboy, :prepopulate, 3, [file: '/Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl', line: 304]}, {:poolboy, :init, 3, [file: '/Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl', line: 153]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
** (MatchError) no match of right hand side value: {:error, {:wallaby, {{:shutdown, {:failed_to_start_child, Wallaby.Phantom, {:shutdown, {:failed_to_start_child, Wallaby.ServerPool, {{:badmatch, {:error, {:timeout, {Task, :await, [%Task{owner: #PID<0.986.0>, pid: #PID<0.988.0>, ref: #Reference<0.1593646549.2667839490.39908>}, 5000]}}}}, [{:poolboy, :new_worker, 1, [file: '/Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl', line: 283]}, {:poolboy, :prepopulate, 3, [file: '/Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl', line: 304]}, {:poolboy, :init, 3, [file: '/Users/andrew/Projects/groupcollect/test_project_1_4/deps/poolboy/src/poolboy.erl', line: 153]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}}}, {Wallaby, :start, [:normal, []]}}}}
    test/test_helper.exs:2: (file)
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
```

This error always occurs and prevents me from running my acceptance test suite. As mentioned above, there are no issues for me on wallaby 0.19.1. 

## Environment

```
Erlang 21.1
Elixir 1.8.1
Phantomjs 2.1.1
Wallaby 0.19.2
```

To make this easier to reproduce, I created a minimal phoenix project that reproduces this issue (for me at least). Just check out [AndroidOatmeal/wallaby-poolboy-error-20190405](https://github.com/AndroidOatmeal/wallaby-poolboy-error-20190405), and try running `mix test`.

**Comment by AndroidOatmeal** [comment]
I was able to get a bit more information by enabling `handle_otp_reports: true` and `handle_sasl_reports: true` in my logger config. I'm attaching the full version of the timeout
[full_wallaby_error.log](https://github.com/keathley/wallaby/files/3049137/full_wallaby_error.log)
 error.

**Comment by keathley** [comment]
Thanks for the detailed report @AndroidOatmeal. I can hopefully take a look at this soon to see if I can figure out what's going on. We've been seeing more and more issues with phantom driver recently and I'm not sure if we changed something or if phantom changed something. It's also complicated because we're trying to steer folks towards chromedriver since it tends to have less issues. Regardless I'll see if I can figure out what's up.

**Comment by mhanberg** [comment]
@AndroidOatmeal are you still seeing this behavior while using the latest version?

**Comment by AndroidOatmeal** [comment]
@mhanberg I have since switched from PhantomJS to Chromedriver. I'll close this for now. Thanks!

**Comment by aaronrenner** [comment]
This is still an intermittent issue in our CI pipeline:

https://github.com/aaronrenner/wallaby/runs/433741444#step:6:67
https://github.com/elixir-wallaby/wallaby/pull/510/checks?check_run_id=433928165#step:6:70

**Comment by mhanberg** [comment]
Closing this since we don't use poolboy anymore
