### ISSUE TITLE
Simulate Drag and Drop Between Elements

### ISSUE THREAD

**Issue by zolrath** [elixir-wallaby/wallaby#43]
It would be nice to be able to test drag and drop interactions with wallaby easily by specifying a selector to drag and the selector it should be dropped upon.

**Comment by keathley** [comment]
What sort of api were you thinking about for this? I'd be interested to see a sample implementation. Otherwise if this is an issue you're facing right now you can always use `execute_script/2` and just do drag and drop directly with JS.

**Comment by zolrath** [comment]
I would think it would be nice to separate the drag and drop actions to allow partial application for reuse.
```
session
|> drag("#garbage")
|> drop("#trash")
```
This way you could save off everything before the drop into a function and call it with a new drop target easily for multiple tests.

**Comment by keathley** [comment]
I think the way we'd have to do this is with the perform actions endpoint: https://www.w3.org/TR/webdriver/#dfn-perform-actions.

We'd have to construct the list of actions internally and then execute them. I'm not sure what the level of effort would be to construct the actions since I'm not exactly sure what format the actions have to be in or if they would work with our existing functionality.

**Comment by michallepicki** [comment]
Selenium JSON Wire Protocol has some touch-related commands (see [Selenium Wiki](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchscroll) and I am currently using `touch_scroll` like this:

```

  def touch_scroll(session, element, x_offset, y_offset) do
    {:ok, _} =
      request(:post, "#{session.url}/touch/scroll", %{
        element: element.id,
        xoffset: x_offset,
        yoffset: y_offset
      })

    session
  end

  def touch_scroll(session, x_offset, y_offset) do
    {:ok, _} =
      request(:post, "#{session.url}/touch/scroll", %{xoffset: x_offset, yoffset: y_offset})

    session
  end
```

We could look into whether this is also supported on chromedriver and add these commands to Wallaby

**Comment by keathley** [comment]
That sounds good to me. I believe that chromedriver had something similar so we can probably take advantage of that.

**Comment by michallepicki** [comment]
Update: @jangromko is working on adding some touch support to Wallaby, we're basing the API on what's available in [Selenium WebDriver Wire Protocol](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchclick) and what works in Chrome (doesn't work in Firefox for some reason). Expect a PR with tests + new commands in a few weeks (similar to https://github.com/keathley/wallaby/pull/453 )

**Comment by oliverswitzer** [comment]
@michallepicki  just checking -- was any progress made on this?

**Comment by michallepicki** [comment]
There is a stale PR by @jangromko , needs to be updated: #480 - @oliverswitzer is this something you'd want to pick up?

**Comment by michallepicki** [comment]
@mhanberg I think this can be closed?

**Comment by mhanberg** [comment]
@michallepicki @jangromko were you ever able to get drag and drop working with the touch commands?

**Comment by michallepicki** [comment]
@mhanberg I think there are different use cases, for some you want the touch commands (naming from `Wallaby.WebdriverClient`) like `touch_down` + `touch_move` + `touch_up`, but for just drag and drop the first PR linked in this issue added regular mouse events support. So there are `button_down` + `move_mouse_to` + `button_up` that can be used for drag and drop. Should be still working since integration tests were added?

**Comment by mhanberg** [comment]
We are trying to do it at work currently, and it is not working, but I was wondering if it has something to do with the JS api we are using to accomplish it.

I also noticed that Capybara still uses some JS to do drag and drop, so I was wondering if it actually worked without the JS haha.

Thanks for the response, I'll take a closer look at our tests.

**Comment by bagrat** [comment]
Are there any updates on this use case?

I am doing something like this:

```
    session
    |> button_down()
    |> move_mouse_by(-300, -200)
    |> button_up()
```

This actually triggers the dragging, and the final location of the moved element is correct.

However, the `drop` event is not triggered on `button_up`, so the whole flow is incomplete. In my use case, if the `drop` is not triggered, I consider the drag to be cancelled and move the element back to its original position. E.g. `drop` is legitimately not triggered when you drag and hit `Esc` before dropping.

**Comment by Menkir** [comment]
I ran into this issue as well and found a solution that helped me.  
My use case was testing the column rearrangement of a table component.  
For this feature, I used the browser’s drag-and-drop event API.

I realized that I first needed to tell the browser where to put my mouse.  
I did this by calling `hover/2`:

```elixir
session
|> hover(Query.css("div.foo"))
|> button_down(:left)
|> move_mouse_by(200, 0)
|> button_up(:left)
```

What confused me was the assumption that I could pass either a `Session` or an `Element`.
I assumed I needed to pass the draggable element, but that didn’t work.
These functions operate on the Session.
