### ISSUE TITLE
Proposal: Deprecate PhantomJS

### ISSUE THREAD

**Issue by mhanberg** [elixir-wallaby/wallaby#437]
## Proposal

PhantomJS has been [officially deprecated](https://github.com/ariya/phantomjs/issues/15344) and should not be the default driver/browser for Wallaby.

I propose to remove PhantomJS as a driver and promote Chrome and Selenium from "Experimental".

This will decrease the surface area of the code base and reduce the support burden.

## Implementation

- [x] Promote Chrome and Selenium as the default drivers and deprecate PhantomJS
- [ ] Remove PhantomJS support

---

cc/ @keathley @michallepicki

**Comment by michallepicki** [comment]
Should we release one version that emits a warning when starting a wallaby session with PhantomJS configured as the driver?

**Comment by michallepicki** [comment]
Are there any features specific to phantomjs that we should try to implement in the webdriver backend first?

**Comment by mhanberg** [comment]
> Should we release one version that emits a warning when starting a wallaby session with PhantomJS configured as the driver?

I think we should.

>Are there any features specific to phantomjs that we should try to implement in the webdriver backend first?

I don't think so.

**Comment by michallepicki** [comment]
@robotlovesyou mostly making sure we make it clear that Chromedriver is the primary backend in documentation, and documenting what's not documented in Chromedriver backend modules

**Comment by mhanberg** [comment]
I will be moving forward with this once #447 is completed.

**Comment by mhanberg** [comment]
I am going to tackle this next.

cc/ @aaronrenner @michallepicki
