### ISSUE TITLE
screenshot_on_failure not being called for `assert_text/2`

### ISSUE THREAD

**Issue by mrcasals** [elixir-wallaby/wallaby#471]
## Issue

Hi! 

I'm trying to get the `screenshot_on_failure` feature working, but I can't get it to work with `assert_text/2`. This happens because the `/2` version of the function does not call the `take_screenshot` one, but the `/3` version does (via `find`):

https://github.com/keathley/wallaby/blob/e15c8b2cf8d4b444a4dea9fd1f33eca161348d15/lib/wallaby/browser.ex#L799-L806

I'll try to submit a PR fixing it!

**Comment by michallepicki** [comment]
Thanks for the report and PR!

I think we're currently researching a different approach, where we'd provide a `feature` macro to replace `test`, which would handle taking screenshots on *any* failure - not just failures in wallaby-provided assertions. You can take a look at [this PR](https://github.com/keathley/wallaby/pull/447) -  let us know if that would work for you and feel free to give any feedback on it you can think of.

**Comment by mrcasals** [comment]
Oh, I was not aware of this, I'll check it!

Thanks!

Should we close this issue and PR then? Or is it valuable at least while #447 is not merged?
