### ISSUE TITLE
Invalid current_path and current_url when using live_redirect (in LiveView)

### ISSUE THREAD

**Issue by bartblast** [elixir-wallaby/wallaby#487]
## Issue

current_path and current_url seem not to take into account live_redirects made through LiveView (they return the URL/path from before the redirect).

## Test Code & HTML

In LiveView:

```
def handle_event("test_event", _, socket) do
{:ok, "test_event_result"} ->
  {:noreply, socket |> live_redirect(to: Routes.live_path(socket, AppWeb.TestComponentLive))}
end
```

In Wallaby test case:

`assert current_path(session) == "/path-after-redirect"`

PS:
I also implemented the same case in Cypress and it works correctly.

**Comment by michallepicki** [comment]
Hi!

Can you provide a minimal LiveView repository with a test that reproduces this issue?

I'm not sure this is a problem with Wallaby at all but this way we'll be able to quickly check and see.

My first thought is that it is a timing issue, and Wallaby may be checking the URL before the page got redirected. In this case, you'd need to add some sleeps or waiting loops in your test code.

**Comment by bartblast** [comment]
It turned out that I used the timer incorrectly (I assumed, not sure why ;) that it uses seconds instead of microseconds). Increasing the timeout fixed the issue.
