### ISSUE TITLE
Add retry

### ISSUE THREAD

**Issue by danyflorez** [elixir-wallaby/wallaby#529]
## Issue

If a test fail it doesn't retry the test, can we add the retry number by configuration?

**Comment by mhanberg** [comment]
I think that is more of a request for ExUnit, rather than Wallaby.

What do you think @aaronrenner?

**Comment by danyflorez** [comment]
Do you have any idea how can I develop it myself?

**Comment by mhanberg** [comment]
Running your tests like so will retry failed tests up to 2 additional times

```shell
$ mix test || mix test --failed || mix test --failed
```

**Comment by danyflorez** [comment]
Wow, that's great! Thanks you're the best @mhanberg
