### ISSUE TITLE
Can Wallaby be used outside of tests, as a web scraper?

### ISSUE THREAD

**Issue by camstuart** [elixir-wallaby/wallaby#530]
## Question

Hello, I am just wondering if it is possible to use Wallaby external to tests, in my case I would like to html scrape some pages that first require a login.

So Ideally I would be able to maintain session cookies to use on each request

**Comment by aaronrenner** [comment]
Absolutely! You'll want to add it to your dependencies without `runtime: false` so it starts automatically:
```elixir
def deps do
  [{:wallaby, "~> 0.24.0"}]
end
```

Let me know if you run into any problems!

**Comment by mhanberg** [comment]
Closing this because it is not an issue, but feel free to continue discussion.

**Comment by jswny** [comment]
Since it calls ExUnit code directly, this fails in releases unfortunately :/ I'm looking for a way to include ExUnit in the release to get around this currently.

```18:15:03.703 [info]  Application wallaby exited: Wallaby.start(:normal, []) returned an error: shutdown: failed to start child: Wallaby.SessionStore
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function ExUnit.after_suite/1 is undefined (module ExUnit is not available)
            ExUnit.after_suite(#Function<0.96164278/1 in Wallaby.SessionStore.init/1>)
            (wallaby 0.28.0) lib/wallaby/session_store.ex:41: Wallaby.SessionStore.init/1
            (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3```

**Comment by shulhi** [comment]
> Since it calls ExUnit code directly, this fails in releases unfortunately :/ I'm looking for a way to include ExUnit in the release to get around this currently.
> 
> ```
>     ** (EXIT) an exception was raised:
>         ** (UndefinedFunctionError) function ExUnit.after_suite/1 is undefined (module ExUnit is not available)
>             ExUnit.after_suite(#Function<0.96164278/1 in Wallaby.SessionStore.init/1>)
>             (wallaby 0.28.0) lib/wallaby/session_store.ex:41: Wallaby.SessionStore.init/1
>             (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
>             (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
>             (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3```
> ```

Were you able to fix this error? I'm having the same issue.

**Comment by jswny** [comment]
> > Since it calls ExUnit code directly, this fails in releases unfortunately :/ I'm looking for a way to include ExUnit in the release to get around this currently.
> > ```
> >     ** (EXIT) an exception was raised:
> >         ** (UndefinedFunctionError) function ExUnit.after_suite/1 is undefined (module ExUnit is not available)
> >             ExUnit.after_suite(#Function<0.96164278/1 in Wallaby.SessionStore.init/1>)
> >             (wallaby 0.28.0) lib/wallaby/session_store.ex:41: Wallaby.SessionStore.init/1
> >             (stdlib 3.14) gen_server.erl:417: :gen_server.init_it/2
> >             (stdlib 3.14) gen_server.erl:385: :gen_server.init_it/6
> >             (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3```
> > ```
> 
> @jswny Were you able to fix this error? I'm having the same issue.

Yes! It's probably a bad solution, but I start ExUnit in my releases like so:
```elixir

  def releases() do
    [
      myapp: [
        applications: [ex_unit: :permanent]
      ]
    ]
  end
```

This is the only solution I could find :/

**Comment by DeedleFake** [comment]
I'm using Wallaby in this way and it seems to be leaving large numbers of Chrome instances lying around in the background if I restart my app, which I've been doing a lot during development. I found #578, but that only applies to tests. Is there a good way to make sure that all of the background Chrome processes exit when the OTP application does? I've just been manually running `killall chrome`.

**Comment by marceldegraaf** [comment]
Same here, @DeedleFake. I tried killing the Wallaby sessions manually, but even then a bunch of `chrome` processes remain.

When starting the app with `iex -S mix` I see the pool of `chromedriver` processes that Wallaby creates, but no `chrome` processes are running yet, as expected.

```elixir
iex(1)> {:ok, pid} = MyApp.Browser.start_link()
```

This is a simple Agent process that keeps a Wallaby session in its state, so it can be re-used throughout my application. If I now run `ps aux | grep chrome` I see a bunch of `chrome` processes, started by one of the `chromedriver` processes from Wallaby's pool.

```elixir
iex(2)> Wallaby.SessionStore.list_sessions_for |> List.first |> Wallaby.WebdriverClient.delete_session()
```

Having killed the Wallaby session, I expect the `chrome` processes to be gone. However, a quick `pstree -p` shows a `chrome` process running, that has moved under PID 1 (systemd).
