### ISSUE TITLE
How to update to Wallaby v.0.24.0 while using Chrome Headless?

### ISSUE THREAD

**Issue by ryanzidago** [elixir-wallaby/wallaby#531]
After reading the CHANGELOG.md, I see the following instructions: 

> Moves configuration options for using chrome headlessly, the chrome binary, and the chromedriver binary to the :chromedriver key in the :wallaby application config.

Before wanting to update to 0.24.0, I had the following code in `test.exs`:
```
config :wallaby,
  driver: Support.Wallaby.Experimental.Chrome,
  chrome: [headless: true]
```

Now, I tried what is currently written on [hex.docs](https://hexdocs.pm/wallaby/Wallaby.Experimental.Chrome.html#module-headless), namely doing that:

```
config: wallaby,
  chromedriver: [driver: Support.Wallaby.Experimental.Chrome, headless: true]
```

However, I still get this error: 
```
** (MatchError) no match of right hand side value: {:error, {:wallaby, {:bad_return, {{Wallaby, :start, [:normal, []]}, {:EXIT, {%Wallaby.DependencyError{message: "Wallaby can't find phantomjs. Make sure you have phantomjs installed\nand included in your path, or that your `config :wallaby, :phantomjs`\nsetting points to a valid phantomjs executable.\n"}, [{Wallaby, :start, 2, [file: 'lib/wallaby.ex', line: 33]}, {:application_master, :start_it_old, 4, [file: 'application_master.erl', line: 277]}]}}}}}}
    test/test_helper.exs:1: (file)
    (elixir 1.10.3) lib/code.ex:926: Code.require_file/2
    (elixir 1.10.3) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.10.3) lib/enum.ex:783: Enum.each/2
```

**Comment by ryanzidago** [comment]
After reading this [line of code](https://github.com/elixir-wallaby/wallaby/blob/d075c456d379f97de385a65ab063c2e08e2ad47f/lib/wallaby.ex#L114), I realized that the env variable `WALLABY_DRIVER` was not set to `chrome`.

If I run the tests like this: `WALLABY_DRIVER=chrome mix test`, then the tests work. 

However, there must be a simpler way or?

**Comment by mhanberg** [comment]
`driver` is still a top level key. 

Your config should be 

```elixir
config :wallaby,
  driver: Wallaby.Experimental.Chrome,
  chromedriver: [headless: true]
```

**Comment by ryanzidago** [comment]
Indeed, thank you @mhanberg!
