### ISSUE TITLE
Chrome zombie processes

### ISSUE THREAD

**Issue by axelson** [elixir-wallaby/wallaby#544]
## Issue

I'm using these versions:
```
wallaby 0.26.2
erlang 23.0.2
elixir 1.10.2-otp-22
ChromeDriver 83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}) (installed via homebrew cask)
Mac OS 10.14.6
```

After running any Wallaby test I get zombie chrome processes, this happens even if the test executes successfully. While the test is running the Google Chrome OS Processes are children of a beam.smp process, but after the test finishes their parent process ID is 1 (init).

## Test Code & HTML

N/A

Related: https://github.com/elixir-wallaby/wallaby/issues/367

**Comment by mhanberg** [comment]
Hi Jason, thanks for taking the time to open an issue.

I have a few questions.

- How many tests are in your suite?
- Does this happen when running a single test? Multiple tests? The whole test suite?
- Are you running your tests `async: true`?
- If yes, how many test modules to you have?

**Comment by axelson** [comment]
This is running a single test with `async: false`. I am testing a Phoenix LiveView application so perhaps that's causing an issue. Perhaps the websocket causes the chrome instance to not close down?

**Comment by mhanberg** [comment]
Do you think you can make a minimal reproduction project that I could clone to investigate?

**Comment by axelson** [comment]
@mhanberg here's a reproduction repository: https://github.com/axelson/wallaby_repro

I haven't narrowed it down but the zombie processes don't occur quite as often as I initially thought.

**Comment by mhanberg** [comment]
It works (or, doesn't work 😝) for me. Thanks, the reproduction repo really helps!

**Comment by miquecg** [comment]
This happens to me also. After running the test suite I can see many chromium processes hanging from PID 1.

```
erlang 22.3.4.3
elixir 1.10.4
wallaby 0.26.2
chromium-driver 83.0.4103.116 (installed from Debian repos)
Debian 10.4
```

I first noticed something was going on when I saw server log messages about invalid tokens sent by my app.js and tests were always ok. Messages were showing up intermittently and after killing all chromium processes they were gone, so I presume one of those stale sessions was still running some cached JavaScript.

**Comment by braunse** [comment]
I got the same phenomenon on Debian buster, with

```
erlang 23.1.1
elixir 1.11.2
wallaby 0.26.2
chromium 86.0.4240.183 (installed via Nix)
```

Chromium processes start hanging off systemd and interfering with the test suite (executing outdated javascript).

What can I do to contribute to a fix (knowing nothing about Wallaby's internals)? Having to run my test suite as `mix test ; killall chromium` does not feel like something I should be proud of, so if there's anything I can do to help, I'd like to do so.
