### ISSUE TITLE
Wallaby 0.26.2, chromedriver issue ** (exit) exited in: GenServer.call(Wallaby.Chrome.Chromedriver, :wait_until_ready, 5000) 

### ISSUE THREAD

**Issue by reneweteling** [elixir-wallaby/wallaby#546]
## Issue

Running locally MacOs (Elixir 1.10.3 OTP 23, chromedriver 83) all is working in the world, but running the tests in our alpine container things get messy.

The error message:
```
 ** (exit) exited in: GenServer.call(Wallaby.Chrome.Chromedriver, :wait_until_ready, 5000)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

Then ive did some digging and i saw this error message popping up:

```
10:22:48.180 [error] GenServer Wallaby.Chrome.Chromedriver terminating
** (FunctionClauseError) no function clause matching in Keyword.fetch!/2
    (elixir 1.10.3) lib/keyword.ex:396: Keyword.fetch!(nil, :os_pid)
    (wallaby 0.26.2) lib/wallaby/chrome/chromedriver/server.ex:101: Wallaby.Chrome.Chromedriver.Server.handle_continue/2
    (stdlib 3.13) gen_server.erl:680: :gen_server.try_dispatch/4
    (stdlib 3.13) gen_server.erl:431: :gen_server.loop/7
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:continue, :start_chromedriver}
``` 

Running run-command seems to work:
```
/app # sh /app/_build/test/lib/wallaby/priv/run_command.sh
PID: 662
```

Going back to Wallaby 0.24 still functions properly, maybe its an permission issue? Thanks!!

### Environment
Alpine linux 
Elixir 1.10.3 OTP 23
ChromeDriver 83.0.4103.116

**Comment by rickclare** [comment]
Yes, we are encountering the same issues and identical error messages, in our CI environment (Alpine Linux in a Docker container).

## Our CI Environment

Alpine Linux (v3.11.6 with edge packages for chromium/chromedriver)
Elixir v1.10.3 OTP 23
Wallaby v0.26.2
Chrome v83.0.4103.116
ChromeDriver v83.0.4103.116

----

As per @reneweteling's experience:

1. Our test specs (with Wallaby v0.26) all execute successfully under a local MacOS environment.
1.  We don't encounter the issue when we rollback the Wallaby version to v0.24 (Wallaby v0.25 does not work for us either).

**Comment by rickclare** [comment]
In case it is of assistance, here is a (simplified) version of our CI Dockerfile:

```Dockerfile
FROM hexpm/elixir:1.10.3-erlang-23.0.2-alpine-3.11.6

ENV LANG=C.UTF-8 \
    HOME=/app \
    MIX_ENV=test

WORKDIR /root

# Install extra Alpine packages (Alpine 'edge')
RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories \
 && apk upgrade --update-cache --available --force-overwrite --quiet --no-progress \
 && apk add --no-cache --quiet --no-progress \
      git build-base util-linux nodejs-current yarn postgresql-client \
      chromium chromium-chromedriver

COPY ["./.", "/app/"]

WORKDIR /app

RUN mix local.hex --force \
 && mix local.rebar --force \
 && mix deps.get \
 && mix deps.compile

RUN mix compile

WORKDIR /app/assets
RUN yarn install && yarn deploy

WORKDIR /app
```

**Comment by reneweteling** [comment]
Any news on this?

**Comment by reneweteling** [comment]
Hiya, any news on this?

**Comment by aaronrenner** [comment]
@reneweteling I just did a little research and bash needs to be installed to get wallaby's run_command.sh wrapper script to work. Let me know if this takes care of the issue for you.

**Comment by reneweteling** [comment]
@aaronrenner All green, thanks man!

So in short, if you are using alpine Linux make sure you install bash

# Dockerfile
```
RUN apk add bash
```

**Comment by rickclare** [comment]
> @reneweteling I just did a little research and bash needs to be installed to get wallaby's run_command.sh wrapper script to work. Let me know if this takes care of the issue for you.

Our CI environment is also fixed, many thanks for the tip @reneweteling !
