### ISSUE TITLE
StaleReferenceException don't cause a failure

### ISSUE THREAD

**Issue by yonst** [elixir-wallaby/wallaby#547]
## Issue
I have a few rows in my app and every row has a button. After the button is pressed the row changes and I want to make sure that the change happened.

## Test Code & HTML

example:
Project: https://stackblitz.com/edit/angular-ivy-mjp3kh
```
def click(session) do
  session
  |> find(css(".row", text: "row3"), &(click(&1, css(".button"))))
  |> validate_row_button_pressed(session)
end

def validate_row_button_pressed(session) do
  row = session
             |> find(css(".row", text: "row3"))
             |> IO.inspect()

  try do
    row
    |> assert_has(css(".button-pressed"))
    |> assert_has(css(".button:disabled")
  rescue
    StaleReferenceException -> :timer.sleep(100)
                                validate_row_button_pressed(session)
  end
end
```
I expected in the case of StaleReferenceException to get an exception so I can try again, but even though the inspect prints:

"%Inspect.Error{message: "got Wallaby.StaleReferenceError with message \"The element you are trying to reference is stale or no longer attached to the\\nDOM. The most likely reason is that it has been removed with Javascript.\\n\\nYou can typically solve this problem by using `find` to block until the DOM is in a\\nstable state.\\n\" while inspecting %{__struct__: Wallaby.Element, driver: Wallaby.Experimental.Chrome, id: \"0.8023033517394649-246\", parent: %Wallaby.Session{driver: Wallaby.Experimental.Chrome, id: \"8a89af15d6fb0b4131b87532e67e259a\", screenshots: [], server: Wallaby.Experimental.Chrome.Chromedriver, session_url: \"http://localhost:56135/session/8a89af15d6fb0b4131b87532e67e259a\", url: \"http://localhost:56135/session/8a89af15d6fb0b4131b87532e67e259a\"}, screenshots: [], session_url: \"http://localhost:56135/session/8a89af15d6fb0b4131b87532e67e259a\", url: \"http://localhost:56135/session/8a89af15d6fb0b4131b87532e67e259a/element/0.8023033517394649-246\"}"}",

instead the assert function don't return exception but wait until timeout...
I try to do it with has_css?, all and so but the same thing happens.

**Comment by mhanberg** [comment]
I think the Inspect error you're seeing is related to #548.

**Comment by yonst** [comment]
> I think the Inspect error you're seeing is related to #548.

I'm not sure you right, in #548 it causing error but in my case it not fail at all...

**Comment by mhanberg** [comment]
You're calling IO.inspect, which is causeing the Inspect error.

**Comment by yonst** [comment]
You right but I expected it to fall in the assert_has function and it didn't happend

**Comment by mhanberg** [comment]
In the code sample above, the test fails on the InspectError when calling `IO.inspect`, so it never reaches the `try` block.

**Comment by yonst** [comment]
In default Inspect error don't cause a failure, so it just print it and keep going
