### ISSUE TITLE
[ChromeDriver] There is no browser window showed

### ISSUE THREAD

**Issue by Koziolek** [elixir-wallaby/wallaby#549]
wallby: 0.26.1 and 0.26.2
chromedriver:  83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416})
elixir: 1.10.0
OTP: 22.2

## Issue

In configuration I have:
```
config :wallaby,
  driver: Wallaby.Chrome,
  chrome: [
    headless: false
  ],
  pool_size: 4 # tested with  pool_size: 1 too
```

Expected behavior → It should show browser window during tests.
Current behavior → no window appears, but all tests pass

**Comment by mhanberg** [comment]
Please see the documentation for configuration headless: https://hexdocs.pm/wallaby/Wallaby.Chrome.html#module-headless
