### ISSUE TITLE
How to list current active sessions ?

### ISSUE THREAD

**Issue by r8code** [elixir-wallaby/wallaby#550]
## Question
Selenium Chrome

Hi , first thank you for this great library 
I want to ask is there any API  to list current active sessions 
I saw there is Wallaby.SessionStore.list_sessions_for   but  if I  had end_session  , the list is not empty 
Is there any way to list current active sessions ? 
Thank you

**Comment by mhanberg** [comment]
There is currently no public API for retrieving the sessions.

Do you mind sharing why you want to get the list of sessions?

**Comment by r8code** [comment]
Hi, I need to retrieving the sessions, to make sure there's no dangling chromedriver port opened by selenium process ,
if I can retrieve the sessions, I can make sure that the current status of selenium is the same as the application
Thanks for the reply

**Comment by bobwaycott** [comment]
I'll chime in here and say I'm also looking for a means of identifying active sessions (and verifying a closed/ended session is truly gone). Use case here is a separate process interacting with webpages in a non-test setting. There could be interaction between the calling process and the `wallaby` process, and want to be able to do something like perform an action using session ID `X`, then when the task is complete, know the session has been truly ended and can't be used again. Noticed the same issue here where I can see all sessions I've ever used in `Wallaby.SessionStore.list_sessions_for/1`, but sessions still appear there after calling `Wallaby.end_session/1`.

**Comment by mhanberg** [comment]
> I saw there is Wallaby.SessionStore.list_sessions_for but if I had end_session , the list is not empty

> Noticed the same issue here where I can see all sessions I've ever used in Wallaby.SessionStore.list_sessions_for/1, but sessions still appear there after calling Wallaby.end_session/1.

I think the case here (ending a session, but not seeing that reflected in the session store) is related to #554.

> Hi, I need to retrieving the sessions, to make sure there's no dangling chromedriver port opened by selenium process ,
if I can retrieve the sessions, I can make sure that the current status of selenium is the same as the application
Thanks for the reply

@r8code I'm not really understanding what you are saying here.

Are you seeing instances of Chrome remaining opening after your test suite finishes?

> I'll chime in here and say I'm also looking for a means of identifying active sessions (and verifying a closed/ended session is truly gone). Use case here is a separate process interacting with webpages in a non-test setting. There could be interaction between the calling process and the wallaby process, and want to be able to do something like perform an action using session ID X, then when the task is complete, know the session has been truly ended and can't be used again.

@bobwaycott I am also not fully understanding what your use case is. Are you using Wallaby for web crawling or something? What do you mean by "non-test setting"?

**Comment by michallepicki** [comment]
For Selenium 3 there's the [GET /sessions](https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessions) endpoint you could call. I haven't tried it but you could probably use it like that:

```
def current_sessions(session) do
  with {:ok, resp} <- Wallaby.HTTPClient.request(:get, "#{session.url}/sessions"),
    {:ok, value} <- Map.fetch(resp, "value"),
  do: {:ok, value}
end
```

Not sure if they expose it for chromedriver, possibly not. The new W3C WebDriver Protocol removed this functionality from their standard (I think this means it's optional).

**Comment by mhanberg** [comment]
I think if you're running concurrent tests, then `/sessions` would return sessions that haven't been started by the current test.

**Comment by bobwaycott** [comment]
@mhanberg Yes, I was evaluating Wallaby as a potential solution versus a Python implementation for interactions between separate applications. The particular use case is `ElixirApp1` sends a request to `ElixirApp2`, which interacts with a given page, and communicates results back to `ElixirApp1`. I wasn't seeing anything particular about Wallaby that would prevent such a non-test-running use case, as it's relying on Selenium just like the comparable Python implementation. Because this use case requires the two Elixir apps to communicate back and forth, there's a need to reuse a given session for the duration of a particular action—and I wanted to verify that any started session was actually ended when the task was complete.

**Comment by r8code** [comment]
@mhanberg yes the use case is for testing other external website (like web crawling behaviour) ,
Hound  library  has Hound.SessionServer for mapping the current process with selenium session and  Hound.Session.active_session/0 , which basically just requesting  GET to  /sessions API ,
I'll try to make pull request ,
Thanks

**Comment by mhanberg** [comment]
@bobwaycott Re:your edit. Yep, the ets table is where I think the bug is. I'll be able to provide a fix in the next few days.

**Comment by mhanberg** [comment]
For now, you can use `Wallaby.SessionStore.list_sessions_for/1` to get the current active sessions, however please remember that this is private API as of right now.
