### ISSUE TITLE
Unable to create session with JavascriptEnabled set to true

### ISSUE THREAD

**Issue by ChipCoons** [elixir-wallaby/wallaby#551]
## Issue

I'm unable to set javascript enabled in the session either with a parameter passed in on session create, i.e.:

`{:ok, session} = Wallaby.start_session([%{javascriptEnabled: true}])`

or by setting in the config.exs :

`config :wallaby,
  driver: Wallaby.Chrome,
  chromedriver: [
    javascriptEnabled: true
  ]`

I'm probably overlooking something simple, but have been unsuccessful in digging out more information in any of the docs or code, so I'm not certain if this is a bug or oversight on my part.

**Comment by mhanberg** [comment]
Hi, you are missing the `capabilities` key in the keyword list you passed to `start_session`.

**Comment by ChipCoons** [comment]
Do the capabilities need to be fully enumerated?  If I use:

` {:ok, session} = Wallaby.start_session([capabilities: [ %{javascriptEnabled: true}]])`

I get an invalid session id error.

**Comment by mhanberg** [comment]
The capabilities are a map. 


`{:ok, session} = Wallaby.start_session(capabilities: %{javascriptEnabled: true})`

**Comment by ChipCoons** [comment]
Thanks.  It would be nice if a sample of customizing the session was documented someplace.

**Comment by mhanberg** [comment]
The options are documented here https://hexdocs.pm/wallaby/Wallaby.Chrome.html#content. 

Feel free to submit a PR if they're not clear enough!
