### ISSUE TITLE
Add the ability to add macros on top of wallaby

### ISSUE THREAD

**Issue by danyflorez** [elixir-wallaby/wallaby#552]
## Issue

I'd like to extend the functionality of wallaby so I need to add a macro to run some code before and after the test execution.

Thanks.

**Comment by mhanberg** [comment]
Is there something specific you can't do using the callbacks provided by ExUnit?

**Comment by danyflorez** [comment]
Yeah my team is thinking about implementing retry as macros, something like 

  use ExUnit.Case, async: true
  use Wallaby.Feature
  use Common.Retry

 retryable_feature "This is gonna fail sometimes", %{session: session} do
   ...some code
 end

**Comment by mhanberg** [comment]
Is the solution I offered to you previously not sufficient? https://github.com/elixir-wallaby/wallaby/issues/529#issuecomment-627035449

**Comment by danyflorez** [comment]
Sadly it wasn't approved by the architecture team :(

**Comment by mhanberg** [comment]
If you want to implement your own version of `feature` that incorporates retries, you're more than welcome to copy the code into your code base and modify it to do so. 

If it works well for you, we can talk about whether it should be upstreamed into Wallaby.

**Comment by danyflorez** [comment]
Great, I'm gonna try my best, thanks
