### ISSUE TITLE
Integration with Mox?

### ISSUE THREAD

**Issue by chrisgreg** [elixir-wallaby/wallaby#553]
Trying to mock out some external API's that get called as part of the E2E journey doesn't seem to be working with Wallaby - it works fine for standard Phoenix controller tests.

Is there something special that needs to be done or does the separate session interfere with how Wallaby works?

**Comment by mhanberg** [comment]
Do you mind sharing a code snippet or maybe share a repo that demonstrates Mox not working with a Wallaby test?

**Comment by keathley** [comment]
You might have to put mox into global mode.

**Comment by anduonghien** [comment]
Can we integrate https://github.com/parroty/exvcr with Wallaby

**Comment by mhanberg** [comment]
> Can we integrate https://github.com/parroty/exvcr with Wallaby 

@anduonghien can you please open a new issue regarding this, and explain what your problem is and why an integration with Wallaby would solve it?

**Comment by anduonghien** [comment]
Sorry for a late reply @mhanberg, I have create a new issue for it at https://github.com/elixir-wallaby/wallaby/issues/557, please have a look when you have time and let me know if it's not clear, thanks you. 🙏

**Comment by mhanberg** [comment]
@chrisgreg I've just merged in some instructions on how to use Mox, Phoenix, and Wallaby together in harmony. https://github.com/elixir-wallaby/wallaby/pull/592
