### ISSUE TITLE
second session does not close when test finishes

### ISSUE THREAD

**Issue by cysiegel** [elixir-wallaby/wallaby#554]
Hi 

Thank you again for this great library

After an elixir test with multiple sessions finishes (whether success or fail) the second session remains open  

![image](https://user-images.githubusercontent.com/37839547/88524214-b8ab4c00-d001-11ea-8130-89a55324b021.png) 
(what my docker looks like after a while)  

Using Wallaby `0.26.2`, chrome driver, elixir `1.10.4` and running on a mac
We are not using the Feature module    
```
  setup_all do
    {:ok, user} = Wallaby.start_session([capabilities: %{browserName: "chrome"}])
    {:ok, admin} = Wallaby.start_session([capabilities: %{browserName: "chrome"}])
  
    %{sessions: %{user: user, admin: admin}
  end

  test "do a test", sessions do
     sessions
     |> user_function()
     |> admin_function()
  end
```

Just as an aside - It seems funny to use the Feature Module when testing multiple features (like an end to end test)  - as it is not testing a feature but many features

Is it possible to give back the ability for automatic screenshots on error when not using the Feature Module?

Thanks

**Comment by mhanberg** [comment]
Couple of things,

- Can you provide a repo with a test that reproduces the problem?
- Are you using Wallaby.Selenium or Wallaby.Chrome? If you're using Wallaby.Chrome, you don't need to specify chrome in the capabilities.

>Just as an aside - It seems funny to use the Feature Module when testing multiple features (like an end to end test) - as it is not testing a feature but many features
>
>Is it possible to give back the ability for automatic screenshots on error when not using the Feature Module?

This is unrelated, please open a separate issue for this.

**Comment by cysiegel** [comment]
@mhanberg Thanks for your quick response and for investing so much time in this great library  

I produced a very simple sample repo that reproduces the problem (below)
[sessions_test.zip](https://github.com/elixir-wallaby/wallaby/files/4989554/sessions_test.zip)

The truth is adding `[capabilities: %{browserName: "chrome"}]` was actually legacy code from when we used selenium before selenium had a default -    
but I see now that without specifying chrome the browsers don't open up (it could be its running in headless - except that as you can see in the repo config - its set to `chrome: [headless: false],`)   
Should I open another issue for this?      

I opened up a new issue about the feature name https://github.com/elixir-wallaby/wallaby/issues/556    

Thank you again

**Comment by mhanberg** [comment]
the configuration for running chrome headlessly can be seen here: https://hexdocs.pm/wallaby/Wallaby.Chrome.html#module-headless

**Comment by mhanberg** [comment]
I think I have figured out the problem, and it I think it is also the cause of #544.

I'll be implement a fix in the next couple days.

**Comment by mhanberg** [comment]
Thanks for providing the reproduction project!
