### ISSUE TITLE
Feature Module name 

### ISSUE THREAD

**Issue by cysiegel** [elixir-wallaby/wallaby#556]
It looks like Wallaby is now going in the direction of using the Feature Module instead of using the built in elixir `test`     
(Automatic screenshots now only occur inside the feature macro)

It seems funny to always put our tests in something named `feature` when testing multiple features (like an end to end test) - as it is not testing a feature but the combination of many features together

**Comment by mhanberg** [comment]
I think that this is being slightly pedantic or too specific as to what constitutes a feature.

I might say a feature is "user can create a new post", but that involves signing in, navigating to the page, typing in the post text, typing in a name, clicking submit, being redirecting to the index page.

Is that one feature or 4-6 features?

The only other name that I have seen people use to name their exunit case template has been `AcceptanceCase`, but I think `Wallaby.Acceptance` and `acceptance "user can do a thing", %{session: session} do` doesn't sound as good IMO.
