### ISSUE TITLE
chromedriver: [headless: false] not working anymore with Chromedriver 85

### ISSUE THREAD

**Issue by reneweteling** [elixir-wallaby/wallaby#568]
## Issue

Chromedriver 85 is not booting chrome when headless is set to false. Tests work fine though.

## Test Code & HTML

```elixir
# test.exs

config :wallaby,
  otp_app: :mc_mms,
  driver: Wallaby.Chrome,
  chromedriver: [
    headless: false
  ],
  log: true,
  screenshot_on_failure: true,
  pool_size: 5,
  screenshot_dir: "screenshots"
```

MacOs 10.15.6
Elixir 1.10.3 (compiled with Erlang/OTP 23)
Crome Version 85.0.4183.83 (Official Build) (64-bit)
ChromeDriver 85.0.4183.87 (cd6713ebf92fa1cacc0f1a598df280093af0c5d7-refs/branch-heads/4183@{#1689})
wallaby 0.26.2

**Comment by mhanberg** [comment]
What do you mean by "not booting chrome"? Are you saying that chromedriver does not seem to be respecting the the `headless` setting?

**Comment by reneweteling** [comment]
Exactely, the headless setting is being ignorred. When i inspect the session, i also see that the headless option is there, so that's pretty weird.

Sorry for the unclear explanation.

**Comment by mhanberg** [comment]
Closing this, please comment if you are still experiencing this issue and i'll look into it.

**Comment by l-vincent-l** [comment]
I have the same issue with this configuration and chromedriver 88: 
```
config :wallaby,
 driver: Wallaby.Chrome,
 chromedriver: [
   path: "/snap/bin/chromium.chromedriver",
   headless: false
 ]
```
I have this error : 
```
** (MatchError) no match of right hand side value: {:error, "unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /snap/chromium/1466/usr/lib/chromium-browser/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\n  (Driver info: chromedriver=88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}),platform=Linux 5.4.0-62-generic x86_64)"}
```

```

**Comment by l-vincent-l** [comment]
It wasn’t a wallaby error, but a ubuntu error.

I had to edit `/etc/gdm3/custom.conf` and uncomment `WaylandEnable=false` and reboot.

I hope it can help someone

**Comment by alexslade** [comment]
Our team is experiencing this with chromedriver 100 again. 

```
config :wallaby,
  driver: Wallaby.Chrome,
  chromedriver: [headless: false]
```

Chrome still runs in headless mode, the setting is being ignored. We're investigating and I'll share if we learn anything.
