### ISSUE TITLE
Wallaby.Element.attr("innerHTML") doesn't work anymore with Chromedriver 91.0.4472.19.

### ISSUE THREAD

**Issue by WernerBuchert** [elixir-wallaby/wallaby#597]
## Issue

Wallaby.Element.attr("innerHTML") doesn't work anymore with 91.0.4472.19 (after updating from 90.x.x.x).
I always get nil, although the element is present. The same for outerHTML.

Is there anything known that the Chromedriver in the latest version has changed in this respect?
(BTW. I also did a test with Hound, there it is exactly the same problem, so I kind of assume that the Chromedriver is the problem, but of course I could be completely wrong).

## Details

Elixir: 1.12.0
Erlang: 24.0.1
OS: Ubuntu 18.04
Webdriver (selenium, chromedriver, geckodriver, etc): Chromedriver 91.0.4472.19
Browser (Chrome, Firefox, Safari, etc): Chrome
Local or CI: 

I'm using Wallaby 0.28.0.

**Comment by cysiegel** [comment]
There is a bug with the attribute selector in chromedriver v 91  - see https://bugs.chromium.org/p/chromium/issues/detail?id=1205107      
hopefully they will fix it soon   


In the meantime I came up with an ugly workaround to get an elements value (aside from downgrading chromedriver)
```
  defp get_value_attribute(session, css_string) do
    session
    |> execute_script("val = document.querySelector('#{css_string}').value; document.cookie = 'automation_val=' + val")
    |> cookies()
    |> Enum.find(fn x -> x["name"] == "automation_val" end)
    |> Map.get("value")
  end
  ```
  
  I'm wondering if somebody else came up with something better

**Comment by WernerBuchert** [comment]
Finally there is a new Chromedriver Version: 91.0.4472.101
And it work's again.

**Comment by jcrevits** [comment]
Thanks for the update @WernerBuchert :)
