### ISSUE TITLE
Phoenix 1.16 defaults the test endpoint's server to `false`

### ISSUE THREAD

**Issue by sodapopcan** [elixir-wallaby/wallaby#626]
In Phoenix 1.16-rc.0, the `server` option in the endpoint config is now `false` which causes Wallaby not to work.  Of course, it's still a release candidate so this may or not stick around but I thought I would report.

Here is the config in question in `config/test.exs`:

```elixir
config :my_app, MyAppWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}, port: 4002],
  server: false
```

**Comment by mhanberg** [comment]
That has always been false I believe. In the Wallaby docs, you are instructed to set that to true, to start the web server.
