### ISSUE TITLE
The `Wallaby.Session.t()` typespec is private

### ISSUE THREAD

**Issue by JohnDoneth** [elixir-wallaby/wallaby#628]
## Issue

The `Wallaby.Session.t()` typespec is private which causes issues.

We fail CI when the documentation raises warnings which occurs because the typespec is private.
```
warning: documentation references type "Wallaby.Session.t()" but it is hidden or private
```

I assume the spec is private as the details of the `Wallaby.Session` module should stay hidden but if there was a public `Wallaby.session()` typespec instead that could solve this problem.

**Comment by mhanberg** [comment]
I have noticed this as well.

Did you start seeing this with v0.29.0?

**Comment by JohnDoneth** [comment]
We are currently using version `0.28.1`.

**Comment by mhanberg** [comment]
What Elixir and OTP version are you using?

**Comment by JohnDoneth** [comment]
erlang 24.0.5
elixir 1.12.2-otp-24

**Comment by mhanberg** [comment]
Did you happen to just update to either elixir 1.12 or otp 24?

**Comment by mhanberg** [comment]
I am not able to reproduce this.

Does this happen when running your test suite? are you building docs? running dialyzer?

**Comment by JohnDoneth** [comment]
> are you building docs?

Yes when running `mix docs` we encounter the above issue. We have some helper functions to work with Wallaby that have `Wallaby.Session.t()` as a spec, like the library itself. 
![image](https://user-images.githubusercontent.com/3239951/133537581-fc7d99b6-235c-4584-a66c-dc659997f164.png)
 When those are documented, they raise the error because the spec is not public.

We've fallen back to using `%Wallaby.Session{}` in those specs which works but is not ideal. It would be nice to have a public typespec for Wallaby Session since it's passed around the public API but is private.

For example, multiple public API calls take a session but aren't typespec'd as taking one. Adding specs to those would be a nice improvement.
![image](https://user-images.githubusercontent.com/3239951/133537876-fe35d3d8-3fd8-457b-a108-cbc277e6084a.png)

Some of the functions do have a `session()` typespec, but it is also private like `Wallaby.Session.t()` so it has the same issue as mentioned above.
![image](https://user-images.githubusercontent.com/3239951/133538113-5a3364f8-2011-420a-88cb-2ffec9ca73e3.png)

**Comment by mhanberg** [comment]
Ohh, I see.

Are you using Wallaby in production? or are you building docs for your test helpers?
