### ISSUE TITLE
Error when trying to start a new session using Selenium driver

### ISSUE THREAD

**Issue by Qizot** [elixir-wallaby/wallaby#648]
## Issue

When using wallaby with `Selenium` driver I get the following error when trying to start a session:

```
Content-Type header does not indicate utf-8 encoded json: application/json
```
Code causing the problem

https://github.com/elixir-wallaby/wallaby/blob/0fbea3e787e02283e8e2219ea71ddcc4be237e66/lib/wallaby/httpclient.ex#L148

## Details

Elixir: 1.12.3
Erlang: 24.1
OS: MacOS Big Sur 11.5.2
Webdriver: selenium
Browser (Chrome, Firefox, Safari, etc): Chrome and Firefox
Local or CI: Local

Selenium server version: 4.0.0

The same error happens when trying to start a new session when using other http client with the same headers so my first thought was that it is simply missing the charset. When added  to the `lib/wallaby/httpclient.ex` default headers it started to work as expected.

**Comment by goofansu** [comment]
Having the same problem and I confirm #649 fixes the problem.

Elixir: 1.13.3
Erlang: 24.1.7
OS: MacOS Big Sur 11.6.4
Webdriver: selenium 4.1.3 and geckodriver 0.30.0
Browser (Chrome, Firefox, Safari, etc): Firefox
Local or CI: Local
