### ISSUE TITLE
Allow to skip chromedriver-chrome version match check

### ISSUE THREAD

**Issue by michallepicki** [elixir-wallaby/wallaby#697]
After https://github.com/elixir-wallaby/wallaby/pull/688 got merged, Wallaby no longer works with chromium on Linux (I think it will not work with a custom installation path on Windows either).

One solution would be to allow the chromedirver-chrome version match check to be skipped.

**Comment by mhanberg** [comment]
Are you configuring the chrome binary path or is this with chrome driver finding it on its own?

**Comment by michallepicki** [comment]
> Are you configuring the chrome binary path or is this with chrome driver finding it on its own?

Chromedriver is finding chromium on its own

**Comment by mhanberg** [comment]
I'll try to see if we can make it work with chromium, but if it can't, then adding an option to disable is probably required.

**Comment by mhanberg** [comment]
Released in v0.30.1
