### ISSUE TITLE
Testing live views with chromedriver fails on GitHub actions

### ISSUE THREAD

**Issue by maltekrupa** [elixir-wallaby/wallaby#699]
## Issue

Hi,

I hope this actually is an issue, because so far the only thing I can say is: "works on my machine".😢 

In order to reproduce it, I setup a test repository: https://github.com/maltekrupa/wallaby_test_github_actions

What was done so far in this repository (breaking down the commits):

1. [`mix phx.new wallaby_test_github_actions --no-ecto`](https://github.com/maltekrupa/wallaby_test_github_actions/commit/63c1645b505a1c2baf838675e19aa41ea335065f)
1. [Add a simple live view](https://github.com/maltekrupa/wallaby_test_github_actions/commit/94619119c226a3e5161aca91dcd9c03167b485d3)
1. [Install and configure wallaby](https://github.com/maltekrupa/wallaby_test_github_actions/commit/70070e86f821b63ebc228831f3a06cd996211d50)
1. [Add a test for said live view](https://github.com/maltekrupa/wallaby_test_github_actions/commit/e0f9ab9314e8a7f3f88733d3f3843666fb6c73a9)
1. Confirm it works locally (it does 🤷)
1. [Add GitHub action](https://github.com/maltekrupa/wallaby_test_github_actions/commit/f657729fda34e7dd10ac07346e6c2bdf0ff44586)
1. [Confirm it fails on GitHub actions](https://github.com/maltekrupa/wallaby_test_github_actions/runs/7375804588?check_suite_focus=true)

And now, for whatever reason, the second `assert_has` fails on GitHub after virtually clicking on the `Increment` button.

### Locally

Elixir: 1.13.4
Erlang: 25.0.2
OS: MacOS 12.4
Webdriver (selenium, chromedriver, geckodriver, etc): chromedriver 103.0.5060.53
Browser (Chrome, Firefox, Safari, etc): Google Chrome 103.0.5060.114
Local or CI: Local

### GitHub actions

Elixir: 1.13.4
Erlang: 25.0.2
OS: `ubuntu-latest` on GitHub actions
Webdriver (selenium, chromedriver, geckodriver, etc): [chromedriver 103.0.5060.53](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#browsers-and-drivers)
Browser (Chrome, Firefox, Safari, etc): [Google Chrome 103.0.5060.114](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#browsers-and-drivers)
Local or CI: CI

### Test

[Source](https://github.com/maltekrupa/wallaby_test_github_actions/blob/main/test/wallaby_test_github_actions_web/live/index_live_test.exs)

```elixir
defmodule WallabyTestGithubActionsWeb.IndexLiveTest do
   use ExUnit.Case, async: true
   use Wallaby.Feature

   feature "can increment number", %{session: session} do
     session
     |> visit("/wtga")
     |> assert_has(Query.css("h3", text: "0"))
     |> click(Query.button("Increment"))
     |> assert_has(Query.css("h3", text: "1"))
     |> click(Query.button("Increment"))
     |> click(Query.button("Increment"))
     |> assert_has(Query.css("h3", text: "3"))
   end
 end
```

### HTML

[Source](https://github.com/maltekrupa/wallaby_test_github_actions/blob/main/lib/wallaby_test_github_actions_web/live/index_live.ex#L15-L20)

```html
    <div class="container">
      <form action="#" phx-submit="increment" novalidate>
        <%= submit "Increment", phx_disable_with: "Incrementing..." %>
      </form>
    </div>
    <h3><%= @counter %></h3>
```

## Project that reproduces the bug

https://github.com/maltekrupa/wallaby_test_github_actions

## Random GIF

![](https://media.giphy.com/media/wFOC9RazP97i0/giphy.gif)

**Comment by mhanberg** [comment]
Absolutely amazing bug report!

I'll take a look soon 👍.

**Comment by mhanberg** [comment]
Would you mind turning on automatic screenshots and adding this to the GitHub action so that we can see the screenshot?

```
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Wallaby Screenshots
          path: ./screenshots/
```

**Comment by maltekrupa** [comment]
> Absolutely amazing bug report!

It's the least I can do. :)

> Would you mind turning on automatic screenshots [..]

Not at all. Here you go: https://github.com/maltekrupa/wallaby_test_github_actions/actions/runs/2686408209

I also added you as a collaborator so you can access the artifacts and (if needed) change whatever needs to be changed in the repo.

**Comment by maltekrupa** [comment]
Just saw your fork. Even better.

Thank you for investigating!

**Comment by mhanberg** [comment]
https://github.com/mhanberg/wallaby_test_github_actions/runs/7379446012?check_suite_focus=true

You need to remember to compile your JS assets when running your tests. You can see that this commit fixes the issue.

**Comment by maltekrupa** [comment]
Argh, thank you! It even says so in the readme. Sorry.

**Comment by mhanberg** [comment]
No worries, thanks again for the detailed report 👍
