### ISSUE TITLE
Bug in hexdocs, readme link/expand button not visible

### ISSUE THREAD

**Issue by dvic** [elixir-wallaby/wallaby#701]
Not sure what's going on but https://hexdocs.pm/wallaby/api-reference.html#content

It seems that the readme doesn't have a title

![image](https://user-images.githubusercontent.com/1214337/179934682-19f3ccca-7351-4312-8a30-98c39c11cbd3.png)

**Comment by mhanberg** [comment]
That is strange. Might have to republish the docs. 

But we should also update ex doc to get the new theme and all the latest goodies. 

Feel free to submit a PR if you'd like.

**Comment by dvic** [comment]
Done 👍
