### ISSUE TITLE
Unexpected output to console when running tests

### ISSUE THREAD

**Issue by grantwest** [elixir-wallaby/wallaby#726]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

Mac OS Ventura 13.2.1

### Browser

Chrome

### Driver

chromedriver

### Correct Configuration

- [X] I confirm that I have Wallaby configured correctly.

### Current behavior

When I run the tests I get unexpected output printed to the console:
```
...."phx-F0spwk6Lf_uPnwLi mount:  - " Object
...
```
I created a new Phoenix project with `mix phx.new` using phoenix 1.7.1 and then applied the changes suggested in the Wallaby documentation. I created the simplest possible live view page and then created this test:
```
feature "show index", %{session: session} do
    session
    |> visit(~p"/")
    |> assert_has(Query.text("This is Cider"))
  end
```
The console output has something to do with testing the live view because the non-live view page test that I wrote does not trigger the output. Also, the output does not happen when running phx.server and visiting the page.

### Expected behavior

No output during tests

### Test Code & HTML

See above

### Demonstration Project

https://github.com/grantwest/cider

**Comment by mhanberg** [comment]
Live view turns on JS debug logs by default, you should turn those off during test if you don't want to see them.

**Comment by grantwest** [comment]
@mhanberg Thanks for the quick response! I am new to liveview, how would I turn off the JS debug logs?

**Comment by mhanberg** [comment]
The best place for LiveView help would be the LiveView documentation or asking in the #liveview channel on the Elixir slack.
