### ISSUE TITLE
Modify capabilities while keeping metadata in user agent

### ISSUE THREAD

**Issue by jfpedroza** [elixir-wallaby/wallaby#743]
The beam metadata is only added to the user agent when the default capabilities are used.

The only way I have found to use both is to modify the capabilities using `create_session_fn` but that is marked as deprecated.

Is there any other way to do it?

**Comment by mhanberg** [comment]
Sounds like a bug.

**Comment by jfpedroza** [comment]
I agree. I'll try to solve it.
