### ISSUE TITLE
Is it possible to configure "headless: true | false" at session opening?

### ISSUE THREAD

**Issue by thbar** [elixir-wallaby/wallaby#747]
I am using Wallaby via `Mix.install/2` like this:

```elixir
Mix.install([
  {:wallaby, "~> 0.30.6"}
], config: [
  wallaby: [chromedriver: [headless: true]]
])
```

I quite often need to switch to `headless: false`, which causes a re-compilation in that case.

What is the recommended way to configure this at runtime? Should I pass "capabilities" (with the headless flag) to the Chrome driver, or is there something doable at the session level?

Thanks!

**Comment by mhanberg** [comment]
I believe you can use Application.put_env instead of passing the config into Mix.install

**Comment by thbar** [comment]
You are right - in some cases I believe I had issues with that, so didn't try, but it works perfectly for wallaby! Thanks.

```elixir
Mix.install([
  {:wallaby, "~> 0.30.6"}
])

Application.put_env(:wallaby, :chromedriver, [headless: false])
```
