### ISSUE TITLE
Running wallaby `feature` tests in VS Code

### ISSUE THREAD

**Issue by buildreactive** [elixir-wallaby/wallaby#754]
### Discussed in https://github.com/elixir-wallaby/wallaby/discussions/717

<div type='discussions-op-text'>

<sup>Originally posted by **totaltrash** December  6, 2022</sup>
Anyone using vs code and know of a way to run wallaby features from the code editor?

Not 100% sure, I might have inadvertently installed a testing extension (I recently went wild with extensions for docker and remote development, though there are no installed testing extensions listed for me), and I can now run ex unit tests by hitting the green arrow, but it's not offering the same for features:

![image](https://user-images.githubusercontent.com/637350/206048059-508eaeab-2c97-4f01-b7b9-d75463d4725f.png)
</div>

<sup>Additional details</sup>
Same problem here. May be an issue with ElixirLS plugin, which provides support for "Test discovery, running and debugging via Test Explorer." Might also be that Wallaby isn't providing test hinting... I've no idea which is the case.

Unfortunately the plugin currently completely missed Wallaby `feature` tests – they just don't show up.

VSCode plugin details:
* `ElixirLS: Elixir support and debugger extension`
* version 0.17.10

**Comment by mhanberg** [comment]
I don't think there is anything wallaby can do here, a change needs to happen in the editor tooling.
