### ISSUE TITLE
Screenshot not being saved to `screenshot_dir`

### ISSUE THREAD

**Issue by emarthinsen** [elixir-wallaby/wallaby#791]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.11] [source] [64-bit] [smp:128:32] [ds:128:32:10] [async-threads:1] [jit:ns]

Elixir 1.16.3 (compiled with Erlang/OTP 25)

### Operating system

Linux - NixOS (Channel 24.05)

### Browser

Google Chrome

### Driver

ChromeDriver

### Correct Configuration

- [X] I confirm that I have Wallaby configured correctly.

### Current behavior

I have a super simple Elixir app that uses Wallaby for some browser automation. I'm using it outside of my tests, which is why it doesn't used `Wallaby.Feature`. I'm trying to save my screenshots into the `/tmp` directory, but they always show up in the default `screenshots` directory in my project root. I'm using Wallaby 0.30.9.

Here's my code:

**config/config.exs**
```
import Config

config :wallaby,
       :chromedriver,
       screenshot_dir: "/tmp",
       binary:
         "/nix/store/6dzsvpzbyrn6k6ic24qmz6v2i6zmxji5-google-chrome-130.0.6723.69/bin/google-chrome-stable"
```

**lib/scraper.exs**
```
defmodule Scraper do
  use Wallaby.DSL

  def scrape do
    {:ok, session} = Wallaby.start_session()

    session
    |> visit("https://www.agilecommerce.com")
    |> take_screenshot(name: "testing")
  end
end
```

### Expected behavior

I'd expect a screenshot to appear at `/tmp/testing.png`.

### Test Code & HTML

See above

**Comment by mhanberg** [comment]
Can you double check the permissions on that directory

**Comment by emarthinsen** [comment]
The permissions on that directory were going to cause problems, but that doesn't seem to be an issue. I created a new directory in my home directory and tried to write the screenshots there. I got the same result. They ended up in the `screenshots` folder of my project directory. Here's my updated confix.exs:

```
import Config

config :wallaby,
       :chromedriver,
       screenshot_dir: "/home/eric/tmp",
       binary:
         "/nix/store/6dzsvpzbyrn6k6ic24qmz6v2i6zmxji5-google-chrome-130.0.6723.69/bin/google-chrome-stable"
```

**Comment by mhanberg** [comment]
Oh, I misread. I thought the screenshot was not saving at all before. 

I believe your issue is you are configuring this under the :chromedriver key 

I believe it should be `config :wallaby, screenshot_dir: “some path”`

**Comment by emarthinsen** [comment]
Oh, of course (audible head slap). That was exactly it. Here's my updated `config.exs` for anyone else that runs into the same issue:

```
import Config

config :wallaby,
       screenshot_dir: "/home/eric/tmp",
       chromedriver: [
         binary: "/nix/store/6dzsvpzbyrn6k6ic24qmz6v2i6zmxji5-google-chrome-130.0.6723.69/bin/google-chrome-stable"
       ]
```
